server:
  port: 8086
  tomcat:
    max-threads: 1000
    max-connections: 20000
    min-spare-threads: 30
    accesslog:
      enabled: true
      directory: /opt/log/tomcat_log
    connection-timeout: 30000


spring:
  datasource:
    druid:
      url: jdbc:mysql://106.52.93.16:3306/funtime?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: funtime2019
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5
      max-active: 100
      min-idle: 5
      max-wait: 10000
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: -1
      validation-query: SELECT 1
      validation-query-timeout: 60000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 100000

      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "/druid/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico"
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: funtime@2019
      filter:
        stat:
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 5000
  redis:
    host: 106.52.93.16
    port: 6379
    password: redisredis




mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.rzyou.funtime.entity
logging:
  config: classpath:logback-spring.xml
app:
  pay:
    notifyUrl: https://test.rzyou.com/callback/notifyWxPay
    certPath: /usr/cert/apiclient_cert.p12
    appleUrl: https://sandbox.itunes.apple.com/verifyReceipt
  logpath: /opt/log/pro_log
  im:
    imSdkAppId: 1400323798
    imSdkAppSecret: fe86b9de3bc8f83e011c39286c2977250e4dc7a793e77938a39f0817733109b1
    iosPushCertDevId: 18791
    iosPushCertProdId: 18790



