server:
  port: 8086
  tomcat:
    max-threads: 5000
    max-connections: 20000
    min-spare-threads: 30
    accesslog:
      enabled: true
      directory: /var/local/logs/tomcatlogs
    connection-timeout: 30000


spring:
  datasource:
    druid:
      url: jdbc:mysql://172.17.0.4:3306/funtime?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: !XUNkv4uEps2%7Va%Td5nwT2AIqZUGm8
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5
      max-active: 100
      min-idle: 5
      max-wait: 10000
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: -1
      validation-query: SELECT 1
      validation-query-timeout: 60000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 100000

      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "/druid/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico"
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: funtime@2019
      filter:
        stat:
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 5000
  redis:
    host: 172.17.0.9
    port: 6379
    password: redisredis

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.rzyou.funtime.entity
logging:
  config: classpath:logback-spring.xml
app:
  pay:
    notifyUrl: "http://122.51.172.209:8086/pay/notifyWxPay"
  logpath: /var/local/logs/funtimelogs

