server:
  port: 8086
  tomcat:
    max-threads: 10000
    max-connections: 20000
    min-spare-threads: 30
    accesslog:
      enabled: true
      directory: /var/local/logs/tomcatlogs
    connection-timeout: 30000


spring:
  datasource:
    druid:
      url: jdbc:mysql://172.17.0.4:3306/funtime?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: '!XUNkv4uEps2%7Va%Td5nwT2AIqZUGm8'
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5
      max-active: 100
      min-idle: 5
      max-wait: 10000
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: -1
      validation-query: SELECT 1
      validation-query-timeout: 60000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      log-abandoned: true
      remove-abandoned: true
      remove-abandoned-timeout: 1800
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 100000

      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "/druid/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico"
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: funtime@2019
      filter:
        stat:
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 5000
  redis:
    host: 172.17.0.9
    port: 6379
    password: eKp9rCce4z7rGKPx

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.rzyou.funtime.entity
logging:
  config: classpath:logback-spring.xml
app:
  pay:
    notifyUrl: https://api.rzyou.com/callback/notifyWxPay
    certPath: /usr/cert/zjqF56nqXswklqA8.p12
    appleUrl: https://buy.itunes.apple.com/verifyReceipt
  logpath: /var/local/logs/funtimelogs
  im:
    imSdkAppId: 1400308918
    imSdkAppSecret: 2a299506bb7b6db78f00b8b4c8a16c298e2839eede5f305cad7ab222cec04ca6
    iosPushCertDevId: 18793
    iosPushCertProdId: 18792
