package com.rzyou.funtime.entity;

import lombok.Data;

import java.io.Serializable;
@Data
public class FuntimeImgeCallback implements Serializable {
    private static final long serialVersionUID = 5838911587387612241L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_funtime_imge_callback.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_funtime_imge_callback.trace_id
     *
     * @mbggenerated
     */
    private String traceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_funtime_imge_callback.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_funtime_imge_callback.result
     *
     * @mbggenerated
     */
    private Integer result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_funtime_imge_callback.forbidden_status
     *
     * @mbggenerated
     */
    private Integer forbiddenStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_funtime_imge_callback.porn_info_hit_flag
     *
     * @mbggenerated
     */
    private Integer pornInfoHitFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_funtime_imge_callback.porn_info_score
     *
     * @mbggenerated
     */
    private Integer pornInfoScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_funtime_imge_callback.porn_info_label
     *
     * @mbggenerated
     */
    private String pornInfoLabel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_funtime_imge_callback.porn_info_count
     *
     * @mbggenerated
     */
    private Integer pornInfoCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_funtime_imge_callback.terrorist_info_hit_flag
     *
     * @mbggenerated
     */
    private Integer terroristInfoHitFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_funtime_imge_callback.terrorist_info_score
     *
     * @mbggenerated
     */
    private Integer terroristInfoScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_funtime_imge_callback.terrorist_info_label
     *
     * @mbggenerated
     */
    private String terroristInfoLabel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_funtime_imge_callback.terrorist_info_count
     *
     * @mbggenerated
     */
    private Integer terroristInfoCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_funtime_imge_callback.politics_info_hit_flag
     *
     * @mbggenerated
     */
    private Integer politicsInfoHitFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_funtime_imge_callback.politics_info_score
     *
     * @mbggenerated
     */
    private Integer politicsInfoScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_funtime_imge_callback.politics_info_label
     *
     * @mbggenerated
     */
    private String politicsInfoLabel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_funtime_imge_callback.politics_info_count
     *
     * @mbggenerated
     */
    private Integer politicsInfoCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_funtime_imge_callback.ads_info_hit_flag
     *
     * @mbggenerated
     */
    private Integer adsInfoHitFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_funtime_imge_callback.ads_info_score
     *
     * @mbggenerated
     */
    private Integer adsInfoScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_funtime_imge_callback.ads_info_label
     *
     * @mbggenerated
     */
    private String adsInfoLabel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_funtime_imge_callback.ads_info_count
     *
     * @mbggenerated
     */
    private Integer adsInfoCount;


}